#!/bin/bash
# basic login script -*- shell-script -*-

[ -f ${HOME}/.bash_env ] && \. ${HOME}/.bash_env
[ -f ${HOME}/.bashrc ] && \. ${HOME}/.bashrc

# delete unwanted files
rm -f ~/.shosts ~/.rhosts ~/.bash_history ~/.lesshst

[ "$TERM" = "xterm" ] && title $LOGNAME@$HOSTNAME

[ -z "$TMUX" ] && type tmux >/dev/null 2>&1 && tmux list-sessions 2>/dev/null | sed 's/^/# tmux /'

#last -3 $LOGNAME # | egrep "^$LOGNAME" | sed 's/^/# /' || echo
#echo

# ssh-add -l | egrep -v 'no' \
# || ssh-add 2>&1 | egrep -v 'added' \
# || ssh-add -l | egrep -v 'no'
